### ISSUE TITLE
Unity 2017.2.0f3 OVR Cubemap.CreateExternalTexture arguments wrong

### ISSUE THREAD

**Issue by ChristophHaag** [matryx/calcflow#5]
I think this is part of a plugin from Oculus, so not much for you to do except updating it maybe.

I'm only mentioning it FYI because Unity didn't want to build it because of that one problem:

https://github.com/matryx/calcflow/blob/64118fdf49b691b188ce5e56d3856c4a3ab04272/Assets/OVR/Scripts/OVROverlay.cs#L385

```
-    et = Cubemap.CreateExternalTexture(size.w, size.h, txFormat, mipLevels > 1, isSrgb, externalTex);
+    et = Cubemap.CreateExternalTexture(size.w, txFormat, mipLevels > 1, externalTex);
```

Very surprisingly this Unity version works on Linux:
![screenshot_20171206_043745](https://user-images.githubusercontent.com/781076/33653930-d3dcf3d8-da6e-11e7-894d-864409ce747c.png)
Hopefully it stays that way!

**Comment by shessenauer** [comment]
Hey @ChristophHaag,

Thanks for the reminder. It is just a Unity API change, and we do have a plan for updating to the latest Unity version soon along with additional features! 

Best,
The Nanome Team

**Comment by shessenauer** [comment]
Issue resolved on our side in a previous update
